# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='orphanage',
        ),
        migrations.RemoveField(
            model_name='orphanagedetails',
            name='orphanage',
        ),
        migrations.AlterField(
            model_name='orphanagedetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
